### PR TITLE
Move time parsing to StinkBomb so as not to duplicate work

### PR DESCRIPTION
**Pull request by mockdeep**

### CODE REVIEW

**Comment by mockdeep** [comment]
This is on top of https://github.com/ChalkSchools/stink-bomb/pull/10

**Comment by QuotableWater7** [comment]
also needs merge

**Comment by mockdeep** [comment]
updated

**Comment by golmansax** [comment]
this can be rebased or merge on master now

**Comment by golmansax** [comment]
lgtm to squash merge

**Pull request merged**
